# config/packages/rate_limiter.yaml
framework:
    rate_limiter:
        login:
            policy: 'fixed_window'
            limit: 5
            interval: '1 minute'
            cache_pool: 'cache.app'
