#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#CHEMIN PERMETTANT DE FAIRE AFFICHER LA PAGE ACCUEIL
#AccueilController Nom du Controller
#index   ACTION qui doit être faite
Accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index



#INSCRIPTION UTILISATEUR AVEC TABLE UTILISATEUR
form_inscription_utilisateur:
  path: /utilisateurFormInscription
  controller: App\Controller\UtilisateurController::new



#INSCRIPTION UTILISATEUR 2 AVEC TABLE USER
RegistrationFormType:
  path: /register
  controller: App\Controller\RegistrationController::register



#CONNEXION
app_login:
  path: /login
  controller: App\Controller\SecurityController::login


#DECONNEXION
app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout



#SUPPRESSION DU COMPTE
app_user_delete:
  path: /comptedelete
  controller: App\Controller\UserController::delete








#Redirection vers la page Accueil après la CONNEXION
app_accueil:
  path: /accueil
  controller: App\Controller\AccueilController::index



#Mots de Passe Oublié
app_forgot_password_request:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::request

#Permet de vérifier si l'email est bien compris dans la BDD
app_check_email:
  path: /check-email
  controller: App\Controller\ResetPasswordController::checkEmail






#Permet de faire un reset du MDP
app_reset_password:
  path: /reset/{token}
  controller: App\Controller\ResetPasswordController::reset















# AFFICHER LISTE DES CATEGORIE
app_liste_categorie:
    path: /categorieliste
    controller: App\Controller\CategorieController::list




# AFFICHER LISTE DES ATICLES
app_liste_article:
    path: /articleliste
    controller: App\Controller\ArticleController::list




# AJOUT ARTICLES
app_ajout_article:
    path: /articleajout
    controller: App\Controller\ArticleController::new




# AJOUT CATEGORIE
app_ajout_categorie:
    path: /categorieajout
    controller: App\Controller\CategorieController::new




# AFFICHER MES CATEGORIES
app_mes_categories:
    path: /MesCategories
    controller: App\Controller\CategorieController::mescategories

# MODIFIER MES CATEGORIES
app_modification_categorie:
    path: /categoriemodification/{id}
    controller: App\Controller\CategorieController::edit

# SUPPRIMER UNE CATEGORIE
app_suppression_categorie:
    path: /categoriesuppression/{id}
    controller: App\Controller\CategorieController::delete



# AFFICHER MES ARTICLES
app_mes_articles:
    path: /MesArticles
    controller: App\Controller\ArticleController::mesarticles

# MODIFICATIONS MES ARTICLES
app_modification_article:
    path: /articlemodification/{id}
    controller: App\Controller\ArticleController::edit

# SUPPRESSIONS DE MES ARTICLES
app_suppression_article:
    path: /articlesuppression/{id}
    controller: App\Controller\ArticleController::delete




#POST
#CREER UN POST
app_creer_un_post:
    path: /creationPost
    controller: App\Controller\LancerUnPostController::new


#AFFICHE LA LISTE DES POSTS 
afficher_les_posts:
    path: /afficherLesPosts
    controller: App\Controller\LancerUnPostController::list
















#AFFICHE UN POST EN PARTICULIER
app_affiche_un_post:
    path: /affichePost/{id}
    controller: App\Controller\LancerUnPostController::showpost


#REPONDRE A UN POST
app_repondre_au_post:
    path: /repondreAuPost{id}
    controller: App\Controller\LancerUnPostController::repondreAuPost