#CHEMIN PERMETTANT DE FAIRE AFFICHER LA PAGE ACCUEIL
Accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index


#INSCRIPTION UTILISATEUR AVEC TABLE UTILISATEUR
form_inscription_utilisateur:
  path: /utilisateurFormInscription
  controller: App\Controller\UtilisateurController::new


RegistrationFormType:
  path: /register
  controller: App\Controller\RegistrationController::register

#CONNEXION
app_login:
  path: /login
  controller: App\Controller\SecurityController::login

#DECONNEXION
app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

#SUPPRESSION DU COMPTE
app_user_delete:
  path: /comptedelete
  controller: App\Controller\UserController::delete

#Redirection vers la page Accueil après la CONNEXION
app_accueil:
  path: /accueil
  controller: App\Controller\AccueilController::index

#GET visible dans URL   , - securisé
#POST envoye des données au serveur afin d'effectuer qqch et NON visible ds URL, + securisé
# Mots de Passe Oublié
app_forgot_password_request:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::request
  methods: [GET, POST]

# Permet de vérifier si l'email est bien compris dans la BDD
app_check_email:
  path: /reset-password/check-email
  controller: App\Controller\ResetPasswordController::checkEmail
  methods: [GET]

# Processus d'envoi de l'email de réinitialisation de mot de passe
process_reset_password:
  path: /reset-password/process
  controller: App\Controller\ResetPasswordController::processSendingPasswordResetEmail
  methods: [POST]















# AFFICHER LISTE DES CATEGORIE
app_liste_categorie:
    path: /categorieliste
    controller: App\Controller\CategorieController::list




# AFFICHER LISTE DES ATICLES
app_liste_article:
    path: /articleliste
    controller: App\Controller\ArticleController::list




# AJOUT ARTICLES
app_ajout_article:
    path: /articleajout
    controller: App\Controller\ArticleController::new


#APRES ENREGISTREMENT D'ARTICLE 
article_success:
    path: /articleajout
    controller: App\Controller\ArticleController::new







# AJOUT CATEGORIE
app_ajout_categorie:
    path: /categorieajout
    controller: App\Controller\CategorieController::new



#APRES ENREGISTREMENT D'ARTICLE 
categorie_success:
    path: /categorieajout
    controller: App\Controller\CategorieController::new



# AFFICHER MES CATEGORIES
app_mes_categories:
    path: /MesCategories
    controller: App\Controller\CategorieController::mescategories

# MODIFIER MES CATEGORIES
app_modification_categorie:
    path: /categoriemodification/{id}
    controller: App\Controller\CategorieController::edit

# SUPPRIMER UNE CATEGORIE
app_suppression_categorie:
    path: /categoriesuppression/{id}
    controller: App\Controller\CategorieController::delete



# AFFICHER MES ARTICLES
app_mes_articles:
    path: /MesArticles
    controller: App\Controller\ArticleController::mesarticles



# MODIFICATIONS MES ARTICLES
app_modification_article:
    path: /articlemodification/{id}
    controller: App\Controller\ArticleController::edit

# SUPPRESSIONS DE MES ARTICLES
app_suppression_article:
    path: /articlesuppression/{id}
    controller: App\Controller\ArticleController::delete




#POST
#CREER UN POST
app_creer_un_post:
    path: /creationPost
    controller: App\Controller\LancerUnPostController::new








#AFFICHE UN POST EN PARTICULIER
app_affiche_un_post:
    path: /affichePost/{id}
    controller: App\Controller\LancerUnPostController::showpost


#REPONDRE A UN POST
app_repondre_au_post:
    path: /repondreAuPost{id}
    controller: App\Controller\LancerUnPostController::repondreAuPost




app_mes_posts:
    path: /mes-posts
    controller: App\Controller\LancerUnPostController::mesPosts

supprimer_post:
    path: /supprimer-post/{id}
    controller: App\Controller\LancerUnPostController::supprimerPost














# AFFICHER LISTE DES UTILISATEURS pour le ADMIN
app_liste_comptesUser:
    path: /comptelisteUser
    controller: App\Controller\UserController::listCompteUser





# SUPPRESSION UN USER en tant qu'ADMIN
app_ADMIN_user_delete:
    path: /Adminuserdelete/{id}
    controller: App\Controller\UserController::deleteuser




#Page de Confidentialité
politique_confidentialite:
    path: /politique-confidentialite
    controller: App\Controller\AccueilController::politiqueConfidentialite
   





app_password_request:
    path: /password/request
    controller: App\Controller\ResetPasswordController::request
    methods: [GET, POST]












#User Admin liste des articles
app_liste_articlesUserdepuisAdmin:
    path: /listeArticleUserdepuisAdmin
    controller: App\Controller\UserController::listeArticlesUserdepuisAdmin
   

#User Admin qui peux supprimer des Articles
app_delete_articledepuisAdmin:
    path: /AdminarticlesuppressionUserdepuisAdmin/{id}
    controller: App\Controller\UserController::deleteArticleDepuisAdmin
   


#liste article par utilisateur depuisAdmin
app_user_articles:
    path: /user/{id}/articles
    controller: App\Controller\UserController::userArticles












app_envoyer_message:
    path: /message/send/{username}
    controller: App\Controller\MessageController::showSendMessageForm
    methods: [GET, POST]



showSendMessageForm:
    path: /message/send
    controller: App\Controller\MessageController::showSendMessageForm
    methods: [GET, POST]



list_conversations:
    path: /message/list-conversations
    controller: App\Controller\MessageController::listConversations


list_friends:
    path: /friends
    controller: App\Controller\FriendController::listFriends


reject_friend_request:
    path: /reject-friend-request/{id}
    controller: App\Controller\FriendController::rejectFriendRequest
    methods: ['POST']

accept_friend_request:
    path: /accept-friend-request/{id}
    controller: App\Controller\FriendController::acceptFriendRequest
    methods: ['POST']





app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ResetPasswordController::reset
    methods: [GET, POST]

